version: 2.1

jobs:
  build-and-test:
    working_directory: ~/
    docker:
      - image: frappe/bench
      - image: bitnami/mariadb:10.3
        environment:
          MARIADB_ROOT_PASSWORD: 123
          MARIADB_CHARACTER_SET: utf8mb4
          MARIADB_COLLATE: utf8mb4_unicode_ci
      - image: redis:alpine
    steps:
      - checkout:
          path: /tmp/shopify_integration
      - run:
          name: Setup Bench
          command: |
            chmod +x /tmp/shopify_integration/.circleci/setup.sh
            bash /tmp/shopify_integration/.circleci/setup.sh
      - run:
          name: Run Tests
          working_directory: ~/shopify-bench/sites
          command: |
            bench run-tests --app shopify_integration
  release:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: npx semantic-release

workflows:
  main:
    jobs:
      - build-and-test
      - release:
          filters:
            branches:
              only: master